name: flutter_dictionary
description: Dictionary app using Free Dictionary API.

publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  cupertino_icons: ^1.0.3
  share_plus: ^7.0.2
  http: ^1.1.0
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_riverpod: ^2.3.6
  audioplayers: ^5.0.0
  uuid: ^3.0.7
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  yaml: ^3.1.0
  riverpod_generator: ^2.2.4
  build_runner: ^2.4.6

flutter_launcher_name:
  name: "Dictionary"

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - images/icon.png
